DATA_PATH = "data"
TARP_CSV_FILENAME = f"{DATA_PATH}/TARP.csv"
CLEANED_TARP_CSV_FILENAME = f"{DATA_PATH}/cleaned_tarp.csv"
MODELS_PATH = "models"
MODEL_PICKLE_FILENAME = f"{MODELS_PATH}/model.pkl"

TEST_DATA_PERCENTAGE = 0.2
